 //
// Created by arye on 15/12/2019.
//

#ifndef SIMULATUR_INTERPRETER__CONNECTCOMMAND_H_
#define SIMULATUR_INTERPRETER__CONNECTCOMMAND_H_

class ConnectCommand {

};

#endif //SIMULATUR_INTERPRETER__CONNECTCOMMAND_H_
